# Generated by Django 4.1.5 on 2023-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
